//! Cross-implementation KAT: the canonical TS signer (`packages/pqc/src/slh-dsa-ref.ts`,
//! which self-verifies and matches both the Move verifier and the machine-checked
//! Lean spec) produces (pk, msg, sig); this Rust verifier must accept it.
//!
//! `tests/kat.txt` is generated by `pnpm exec tsx demos/.../gen-kat` (PK=…, MSG=…, SIG=…).
//!
//! STATUS: the verifier in `src/lib.rs` is the salvaged-from-patch starting point
//! and does NOT yet verify (its ADRS byte layout writes keypair@20 instead of the
//! reference's type@16/chain@24/hash@28, and its WOTS checksum hard-codes nibbles
//! instead of a base-w decode). The test is `#[ignore]` until the port matches;
//! un-ignore it as the regression gate once `verify` returns true.

use slh_dsa_lite_verifier::{verify, SlhDsaLitePublicKey, SlhDsaLiteSignature, PK_BYTES};

fn load_kat() -> (Vec<u8>, Vec<u8>, Vec<u8>) {
    let txt = include_str!("kat.txt");
    let mut pk = vec![];
    let mut msg = vec![];
    let mut sig = vec![];
    for line in txt.lines() {
        if let Some(h) = line.strip_prefix("PK=") {
            pk = hex::decode(h.trim()).unwrap();
        } else if let Some(h) = line.strip_prefix("MSG=") {
            msg = hex::decode(h.trim()).unwrap();
        } else if let Some(h) = line.strip_prefix("SIG=") {
            sig = hex::decode(h.trim()).unwrap();
        }
    }
    (pk, msg, sig)
}

#[test]
#[ignore = "WIP port: salvaged verifier does not yet match the reference (ADRS layout + WOTS checksum)"]
fn verifies_reference_signature() {
    let (pk_b, msg, sig) = load_kat();
    assert_eq!(pk_b.len(), PK_BYTES);
    let mut pk_arr = [0u8; PK_BYTES];
    pk_arr.copy_from_slice(&pk_b);
    let pk = SlhDsaLitePublicKey(pk_arr);
    assert!(verify(&pk, &msg, &SlhDsaLiteSignature(sig)), "must accept the canonical TS signature");
}

#[test]
fn rejects_wrong_length_signature() {
    let (pk_b, msg, _) = load_kat();
    let mut pk_arr = [0u8; PK_BYTES];
    pk_arr.copy_from_slice(&pk_b);
    let pk = SlhDsaLitePublicKey(pk_arr);
    assert!(!verify(&pk, &msg, &SlhDsaLiteSignature(vec![0u8; 10])));
}
