/**
 * Generate FIPS-205-flavored Move test vectors for `move/pq_guard`.
 *
 *   tsx packages/pqc/scripts/gen-pq-guard-128s-vectors.ts > move/pq_guard/tests/test_vectors_128s.move
 *
 * Uses @noble/post-quantum's audited SLH-DSA-SHA2-128s signer.  The Move
 * verifier (`slh_dsa_128s::verifier`) was cross-checked byte-exact against this
 * signer in `packages/pqc/src/slh-dsa-128s-ref.test.ts`, so any sig noble
 * produces and the TS reference verifies must also verify on-chain.
 */
import { slh_dsa_sha2_128s } from '@noble/post-quantum/slh-dsa.js';
import { sha256 } from '@noble/hashes/sha256';
import { verify as tsVerify } from '../src/slh-dsa-128s-ref.js';

const TAG = new TextEncoder().encode('PQ_GUARD:UNLOCK:v1');

function hex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

function u64be(v: bigint): Uint8Array {
  const out = new Uint8Array(8);
  let n = v;
  for (let i = 7; i >= 0; i--) {
    out[i] = Number(n & 0xffn);
    n >>= 8n;
  }
  return out;
}

function concat(...parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((a, p) => a + p.length, 0);
  const out = new Uint8Array(total);
  let off = 0;
  for (const p of parts) {
    out.set(p, off);
    off += p.length;
  }
  return out;
}

// Deterministic keygen seed so the generated vectors are stable across runs.
const seed = new Uint8Array(48);
for (let i = 0; i < seed.length; i++) seed[i] = (i * 11 + 23) & 0xff;
const kp = slh_dsa_sha2_128s.keygen(seed);

// Sender address used by the Move test scenario.
const sender = new Uint8Array(32).fill(0x0b);

const action0 = sha256(new TextEncoder().encode('vault::withdraw(1000)'));
const msg0 = concat(TAG, sender, u64be(0n), action0);
const sig0 = slh_dsa_sha2_128s.sign(msg0, kp.secretKey, { extraEntropy: false });

const action1 = sha256(new TextEncoder().encode('vault::withdraw(2500)'));
const msg1 = concat(TAG, sender, u64be(1n), action1);
const sig1 = slh_dsa_sha2_128s.sign(msg1, kp.secretKey, { extraEntropy: false });

// Sanity-check both sides before emitting.
for (const [label, msg, sig] of [
  ['nonce-0', msg0, sig0],
  ['nonce-1', msg1, sig1],
] as const) {
  if (!slh_dsa_sha2_128s.verify(sig, msg, kp.publicKey)) {
    throw new Error(`noble self-verify failed for ${label}`);
  }
  if (!tsVerify(kp.publicKey, msg, sig)) {
    throw new Error(`TS reference verify failed for ${label} — Move would also fail`);
  }
}

const out = `// AUTO-GENERATED by packages/pqc/scripts/gen-pq-guard-128s-vectors.ts
// FIPS-205 SLH-DSA-SHA2-128s vectors for pq_guard tests.  Do not hand-edit.

#[test_only]
module pq_guard::test_vectors_128s;

public fun sender(): address { @0x0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b }

public fun pk(): vector<u8> { x"${hex(kp.publicKey)}" }

public fun action_digest_0(): vector<u8> { x"${hex(action0)}" }
public fun signature_for_nonce_0(): vector<u8> { x"${hex(sig0)}" }

public fun action_digest_1(): vector<u8> { x"${hex(action1)}" }
public fun signature_for_nonce_1(): vector<u8> { x"${hex(sig1)}" }
`;

process.stdout.write(out);
