/**
 * Extract NIST ACVP test vectors for SLH-DSA-SHA2-128s (external interface, pure)
 * and emit Lean theorems that prove our spec's accept/reject matches the
 * official NIST `testPassed` flag for each vector.
 *
 *   curl -sS https://raw.githubusercontent.com/usnistgov/ACVP-Server/master/gen-val/json-files/SLH-DSA-sigVer-FIPS205/prompt.json          -o /tmp/slhdsa-prompt.json
 *   curl -sS https://raw.githubusercontent.com/usnistgov/ACVP-Server/master/gen-val/json-files/SLH-DSA-sigVer-FIPS205/expectedResults.json -o /tmp/slhdsa-expected.json
 *   pnpm exec tsx packages/pqc/scripts/gen-lean-nist-kat.ts > proofs/Fips205/NistKat.lean
 *
 * NIST ACVP provides PASS and FAIL vectors per testGroup: a mix of legitimate
 * signatures and intentionally-malformed ones. We assert both directions.
 */
import { readFileSync } from 'node:fs';
import { slh_dsa_sha2_128s } from '@noble/post-quantum/slh-dsa.js';

const prompt = JSON.parse(readFileSync('/tmp/slhdsa-prompt.json', 'utf-8'));
const expected = JSON.parse(readFileSync('/tmp/slhdsa-expected.json', 'utf-8'));

interface PromptGroup {
  tgId: number;
  parameterSet: string;
  signatureInterface: string;
  preHash: string;
  tests: { tcId: number; pk: string; message: string; signature: string; context?: string }[];
}
interface ExpectedGroup {
  tgId: number;
  tests: { tcId: number; testPassed: boolean }[];
}

// Find the SLH-DSA-SHA2-128s, external, pure test group.
const pg = (prompt.testGroups as PromptGroup[]).find(
  (g) =>
    g.parameterSet === 'SLH-DSA-SHA2-128s' &&
    g.signatureInterface === 'external' &&
    g.preHash === 'pure',
);
if (!pg) throw new Error('no SLH-DSA-SHA2-128s external/pure group in NIST vectors');

const eg = (expected.testGroups as ExpectedGroup[]).find((g) => g.tgId === pg.tgId);
if (!eg) throw new Error(`no expectedResults group for tgId=${pg.tgId}`);

const expectedByTcId = new Map<number, boolean>();
for (const t of eg.tests) expectedByTcId.set(t.tcId, t.testPassed);

// Cross-check each test under noble before emitting (sanity).
function leanHex(hex: string): string {
  return `Fips205.Bytes.hexDecode "${hex.toLowerCase()}"`;
}
function hexToBytes(hex: string): Uint8Array {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}

const skipped: number[] = [];
const validated: { tc: number; ctx: string; pk: string; msg: string; sig: string; pass: boolean }[] = [];

for (const t of pg.tests) {
  const expectedPass = expectedByTcId.get(t.tcId);
  if (expectedPass === undefined) {
    skipped.push(t.tcId);
    continue;
  }
  const pk = hexToBytes(t.pk);
  const msg = hexToBytes(t.message);
  const sig = hexToBytes(t.signature);
  const ctxHex = t.context ?? '';
  const ctxBytes = hexToBytes(ctxHex);

  // noble's verify supports the `context` option (NIST §10.2.2 wrapping).
  let nobleResult: boolean;
  try {
    nobleResult = slh_dsa_sha2_128s.verify(sig, msg, pk, { context: ctxBytes });
  } catch {
    nobleResult = false;
  }
  if (nobleResult !== expectedPass) {
    throw new Error(
      `noble disagrees with NIST expected on tcId=${t.tcId}: noble=${nobleResult}, NIST=${expectedPass}`,
    );
  }
  validated.push({
    tc: t.tcId,
    ctx: ctxHex,
    pk: t.pk.toLowerCase(),
    msg: t.message.toLowerCase(),
    sig: t.signature.toLowerCase(),
    pass: expectedPass,
  });
}

if (skipped.length > 0) {
  process.stderr.write(`[gen-lean-nist-kat] skipped ${skipped.length} tcIds with no expected result\n`);
}

let out = `import Fips205.Verify

/-! # NIST ACVP test vectors for SLH-DSA-SHA2-128s (external, pure)

AUTO-GENERATED by \`packages/pqc/scripts/gen-lean-nist-kat.ts\`. Do not hand-edit.

Source: \`usnistgov/ACVP-Server/gen-val/json-files/SLH-DSA-sigVer-FIPS205/\`
Filtered to: parameterSet = SLH-DSA-SHA2-128s, signatureInterface = external, preHash = pure.

Each \`nist_tc_N\` is one test case from NIST's published vectors. Each
\`nist_passes_N\` / \`nist_fails_N\` theorem proves via \`native_decide\` that
our Lean spec agrees with NIST's official \`testPassed\` flag — i.e. accepts
the legitimate vectors and rejects the intentionally-malformed ones.

This is independent of noble: NIST publishes both the inputs and the
expected outcome, and we verify both.
-/

namespace Fips205.NistKat

open Fips205.Verify

`;

for (const v of validated) {
  out += `def ctx_${v.tc} : ByteArray := ${leanHex(v.ctx)}\n`;
  out += `def pk_${v.tc}  : ByteArray := ${leanHex(v.pk)}\n`;
  out += `def msg_${v.tc} : ByteArray := ${leanHex(v.msg)}\n`;
  out += `def sig_${v.tc} : ByteArray := ${leanHex(v.sig)}\n\n`;
}

out += `/-! ## Acceptance / rejection theorems\n\n`;
out += `These theorems pair each NIST test case with its official expected result.\n`;
out += `Lean's kernel evaluates the verifier and confirms the spec agrees with NIST.\n-/\n\n`;

for (const v of validated) {
  const verb = v.pass ? 'accepts' : 'rejects';
  out += `/-- NIST tcId=${v.tc}: official expected = ${v.pass ? 'PASS' : 'FAIL'} -/\n`;
  out += `theorem nist_${verb}_${v.tc} :\n`;
  out += `    verify pk_${v.tc} msg_${v.tc} sig_${v.tc} ctx_${v.tc} = ${v.pass} := by\n`;
  out += `  native_decide\n\n`;
}

out += `end Fips205.NistKat\n`;

process.stdout.write(out);
process.stderr.write(`[gen-lean-nist-kat] emitted ${validated.length} NIST test cases\n`);
