/**
 * Emit Lean KAT definitions and acceptance/rejection theorems.
 *
 *   pnpm exec tsx packages/pqc/scripts/gen-lean-kat.ts > proofs/Fips205/Kat.lean
 *
 * Generates 10 (pk, msg, sig) tuples with distinct deterministic seeds and
 * distinct messages, plus 4 rejection constructions on the first vector
 * (tampered byte, wrong pk, wrong msg, short sig). Every theorem is proven by
 * Lean's kernel running the verifier under `native_decide`.
 */
import { slh_dsa_sha2_128s } from '@noble/post-quantum/slh-dsa.js';

function hex(bytes: Uint8Array): string {
  let s = '';
  for (let i = 0; i < bytes.length; i++) s += bytes[i]!.toString(16).padStart(2, '0');
  return s;
}

function leanHex(bytes: Uint8Array): string {
  return `Fips205.Bytes.hexDecode "${hex(bytes)}"`;
}

interface Kat {
  index: number;
  pk: Uint8Array;
  secretKey: Uint8Array;
  message: Uint8Array;
  sig: Uint8Array;
}

const KAT_COUNT = 10;
const kats: Kat[] = [];
for (let i = 0; i < KAT_COUNT; i++) {
  // Deterministic seed: each vector derived from `i` so re-runs are stable.
  const seed = new Uint8Array(48);
  for (let j = 0; j < seed.length; j++) seed[j] = (i * 41 + j * 13 + 7) & 0xff;
  const kp = slh_dsa_sha2_128s.keygen(seed);
  const message = new TextEncoder().encode(`FIPS-205 Lean KAT vector #${i + 1}`);
  const sig = slh_dsa_sha2_128s.sign(message, kp.secretKey, { extraEntropy: false });
  if (!slh_dsa_sha2_128s.verify(sig, message, kp.publicKey)) {
    throw new Error(`noble self-verify failed on KAT #${i}`);
  }
  kats.push({ index: i, pk: kp.publicKey, secretKey: kp.secretKey, message, sig });
}

// Sanity-check: the rejections we'll emit really do reject under noble.
const k0 = kats[0]!;
const k1 = kats[1]!;

const tamperedSig = new Uint8Array(k0.sig);
tamperedSig[100] = (tamperedSig[100]! ^ 0xff) & 0xff;
if (slh_dsa_sha2_128s.verify(tamperedSig, k0.message, k0.pk)) {
  throw new Error('noble accepted a tampered sig — should never happen');
}

// Wrong pk: use kat 1's pk for kat 0's sig.
if (slh_dsa_sha2_128s.verify(k0.sig, k0.message, k1.pk)) {
  throw new Error('noble accepted under wrong pk');
}

// Wrong message: use kat 0's sig with kat 1's message.
if (slh_dsa_sha2_128s.verify(k0.sig, k1.message, k0.pk)) {
  throw new Error('noble accepted with wrong message');
}

const shortSig = new Uint8Array(100); // way too short

// ── emit ───────────────────────────────────────────────────────────────────
let out = `import Fips205.Verify

/-! # FIPS-205 SLH-DSA-SHA2-128s KAT vectors (noble-generated)

AUTO-GENERATED by \`packages/pqc/scripts/gen-lean-kat.ts\`. Do not hand-edit.

Each \`kat_N\` def encodes a \`(pk, msg, sig)\` tuple produced by
\`@noble/post-quantum\`'s audited SLH-DSA-SHA2-128s signer. The companion
\`accepts_noble_kat_N\` theorem proves via \`native_decide\` that the Lean
formal spec accepts that tuple — i.e. our spec computes the same function
as the audited reference on that input.

The \`rejects_*\` theorems prove the spec rejects malformed signatures
constructed from \`kat_0\` (tampered byte, wrong pk, wrong msg, short sig).
-/

namespace Fips205.Kat

open Fips205.Verify

`;

for (const k of kats) {
  out += `def pk_${k.index} : ByteArray := ${leanHex(k.pk)}\n\n`;
  out += `def msg_${k.index} : ByteArray := ${leanHex(k.message)}\n\n`;
  out += `def sig_${k.index} : ByteArray := ${leanHex(k.sig)}\n\n`;
}

// Size invariants — fast, no verifier run.
out += '/-! ## Size invariants -/\n';
for (const k of kats) {
  out += `example : pk_${k.index}.size = 32 := by native_decide\n`;
  out += `example : sig_${k.index}.size = 7856 := by native_decide\n`;
}
out += '\n';

// Acceptance theorems — each invokes the full ~2099-call verifier.
out += '/-! ## Acceptance: Lean spec ≡ noble on each KAT -/\n';
for (const k of kats) {
  out += `theorem accepts_noble_kat_${k.index} : verify pk_${k.index} msg_${k.index} sig_${k.index} = true := by\n  native_decide\n\n`;
}

// Rejection: derived from kat 0.
out += `/-! ## Rejection theorems (derived from kat 0)

These prove the verifier rejects malformed signatures. All are
constructed from \`kat_0\` so we share the underlying pk/msg.
-/

def sig_0_tampered : ByteArray := ${leanHex(tamperedSig)}
def short_sig     : ByteArray := ${leanHex(shortSig)}

theorem rejects_tampered_sig : verify pk_0 msg_0 sig_0_tampered = false := by
  native_decide

theorem rejects_wrong_pk : verify pk_1 msg_0 sig_0 = false := by
  native_decide

theorem rejects_wrong_msg : verify pk_0 msg_1 sig_0 = false := by
  native_decide

theorem rejects_short_sig : verify pk_0 msg_0 short_sig = false := by
  native_decide

end Fips205.Kat
`;

process.stdout.write(out);
