/**
 * Generate Move test vectors for `move/slh_dsa`.
 *   tsx packages/pqc/scripts/gen-slh-dsa-vectors.ts > move/slh_dsa/tests/test_vectors.move
 */
import { keygen, sign, packSignature, verify, SLH } from '../src/slh-dsa-ref.js';

function hex(bytes: Uint8Array): string {
  return Array.from(bytes).map((b) => b.toString(16).padStart(2, '0')).join('');
}

const seed = new Uint8Array(SLH.n).fill(0xaa);
const skSeed = new Uint8Array(SLH.n).fill(0xbb);

const { pk, sk } = keygen(seed, skSeed);
const message = new TextEncoder().encode('Move-native SLH-DSA test vector');
const signature = sign(sk, message);
const packed = packSignature(signature);

// Sanity-check: TS-side verify before emitting.
if (!verify(pk, message, signature)) {
  throw new Error('TS-side SLH-DSA verify failed on freshly-generated signature');
}

const pkBytes = new Uint8Array([...pk.seed, ...pk.root]);

const out = `// AUTO-GENERATED by packages/pqc/scripts/gen-slh-dsa-vectors.ts
// SLH-DSA-LITE (n=32, h=8, d=2, h'=4, a=3, k=4). Do not hand-edit.

#[test_only]
module slh_dsa::test_vectors;

/// Public key = PK.seed || PK.root (${2 * SLH.n} bytes).
public fun pk(): vector<u8> { x"${hex(pkBytes)}" }

/// Message that was signed.
public fun message(): vector<u8> { x"${hex(message)}" }

/// Packed signature: FORS bytes || (XMSS layers: wots_sig || auth_path) × d
public fun signature(): vector<u8> { x"${hex(packed)}" }

/// Expected total signature length.
public fun sig_len(): u64 { ${packed.length} }
`;

process.stdout.write(out);
