/**
 * Generate Move test vectors for `move/slh_dsa_128s` using @noble/post-quantum's
 * audited SLH-DSA-SHA2-128s implementation. The Move verifier is byte-exact
 * against this signer (cross-checked via `slh-dsa-128s-ref.test.ts`), so a sig
 * that noble produces and our TS reference verifies must also verify on-chain.
 *
 *   tsx packages/pqc/scripts/gen-slh-dsa-128s-vectors.ts > move/slh_dsa_128s/tests/test_vectors.move
 */
import { slh_dsa_sha2_128s } from '@noble/post-quantum/slh-dsa.js';
import { verify as ourVerify } from '../src/slh-dsa-128s-ref.js';

function hex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

// Deterministic keygen seed so re-runs produce stable vectors.
const seed = new Uint8Array(48);
for (let i = 0; i < seed.length; i++) seed[i] = (i * 7 + 11) & 0xff;
const kp = slh_dsa_sha2_128s.keygen(seed);

const message = new TextEncoder().encode('FIPS-205 SLH-DSA-SHA2-128s on Sui');
// `extraEntropy: false` makes the signature deterministic (R = PK.seed).
const signature = slh_dsa_sha2_128s.sign(message, kp.secretKey, { extraEntropy: false });

// Sanity-check: noble round-trip + our hand-rolled TS verify.
if (!slh_dsa_sha2_128s.verify(signature, message, kp.publicKey)) {
  throw new Error('noble self-verify failed on freshly-generated signature');
}
if (!ourVerify(kp.publicKey, message, signature)) {
  throw new Error('TS reference verify failed — Move verifier would also fail');
}

const out = `// AUTO-GENERATED by packages/pqc/scripts/gen-slh-dsa-128s-vectors.ts
// FIPS-205 SLH-DSA-SHA2-128s.  Signature byte-format: R || FORS || HT.
// Sizes: pk=32, sig=7856, message=${message.length}.
// Do not hand-edit; re-generate with:
//   tsx packages/pqc/scripts/gen-slh-dsa-128s-vectors.ts > move/slh_dsa_128s/tests/test_vectors.move

#[test_only]
module slh_dsa_128s::test_vectors;

/// Public key = PK.seed || PK.root (32 bytes).
public fun pk(): vector<u8> { x"${hex(kp.publicKey)}" }

/// Message that was signed.
public fun message(): vector<u8> { x"${hex(message)}" }

/// FIPS-205 signature: R || FORS || HT.  7856 bytes for the 128s parameter set.
public fun signature(): vector<u8> { x"${hex(signature)}" }

public fun sig_len(): u64 { ${signature.length} }
public fun pk_len(): u64 { ${kp.publicKey.length} }
`;

process.stdout.write(out);
