/**
 * One-shot generator for Move-side WOTS+ test vectors.
 *
 *   tsx packages/pqc/scripts/gen-wots-vectors.ts
 *
 * Prints a self-contained Move test source ready to drop into
 * `move/wots/tests/`. Keeps the Move tests independently runnable and
 * removes any need for the toolchain to load JSON from outside the package.
 */
import { buildAdrs, wotsKeygen, wotsSign, wotsVerify, WOTS } from '../src/wots-ref.js';

function hex(bytes: Uint8Array): string {
  return Array.from(bytes).map((b) => b.toString(16).padStart(2, '0')).join('');
}

function chunked(hexStr: string): string {
  // Move hex literals don't permit whitespace inside the quotes; emit one line.
  return hexStr;
}

const master = new Uint8Array(32).fill(0xa5);
const seed   = new Uint8Array(32).fill(0x5a);
const adrs   = buildAdrs({ keypair: 7 });
const msg    = new Uint8Array(32);
for (let i = 0; i < 32; i++) msg[i] = ((i * 19) ^ 0x42) & 0xff;

const kp  = wotsKeygen(master, seed, adrs);
const sig = wotsSign(kp, msg);

// Sanity check the vector before printing.
if (!wotsVerify(seed, adrs, msg, sig, kp.publicKey)) {
  throw new Error('reference vector failed self-check');
}

const out = `// AUTO-GENERATED by packages/pqc/scripts/gen-wots-vectors.ts
// WOTS+ over SHA-256 (n=32, lg_w=4, len=${WOTS.len}). Do not hand-edit.

#[test_only]
module wots::test_vectors;

public fun seed(): vector<u8> { x"${hex(seed)}" }
public fun adrs(): vector<u8> { x"${hex(adrs)}" }
public fun msg():  vector<u8> { x"${hex(msg)}" }

public fun signature(): vector<u8> {
    x"${chunked(hex(sig), 64)}"
}

public fun public_key(): vector<u8> {
    x"${chunked(hex(kp.publicKey), 64)}"
}
`;

process.stdout.write(out);
