import { sha256 } from '@noble/hashes/sha256';
/**
 * Generate Move test vectors for `move/pq_guard`.
 *   tsx packages/pqc/scripts/gen-pq-guard-vectors.ts > move/pq_guard/tests/test_vectors.move
 */
import { SLH, keygen, packSignature, sign, unpackSignature, verify } from '../src/slh-dsa-ref.js';

const TAG = new TextEncoder().encode('PQ_GUARD:UNLOCK:v1');

function hex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

function u64be(v: bigint): Uint8Array {
  const out = new Uint8Array(8);
  let n = v;
  for (let i = 7; i >= 0; i--) {
    out[i] = Number(n & 0xffn);
    n >>= 8n;
  }
  return out;
}

function concat(...parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((a, p) => a + p.length, 0);
  const out = new Uint8Array(total);
  let off = 0;
  for (const p of parts) {
    out.set(p, off);
    off += p.length;
  }
  return out;
}

const seed = new Uint8Array(SLH.n).fill(0xcc);
const skSeed = new Uint8Array(SLH.n).fill(0xdd);
const { pk, sk } = keygen(seed, skSeed);
const pkBytes = new Uint8Array([...pk.seed, ...pk.root]);

// Sender address (must match the address used in Move tests).
const sender = new Uint8Array(32).fill(0xa);

// First action: nonce=0.
const action0 = sha256(new TextEncoder().encode('vault::withdraw(1000)'));
const msg0 = concat(TAG, sender, u64be(0n), action0);
const sigStruct0 = sign(sk, msg0);
const sig0 = packSignature(sigStruct0);
if (!verify(pk, msg0, unpackSignature(sig0))) {
  throw new Error('TS sanity check: sig0 failed to self-verify after pack/unpack');
}

// Second action at nonce=1, to exercise replay protection in tests.
const action1 = sha256(new TextEncoder().encode('vault::withdraw(2500)'));
const msg1 = concat(TAG, sender, u64be(1n), action1);
const sig1 = packSignature(sign(sk, msg1));

const out = `// AUTO-GENERATED by packages/pqc/scripts/gen-pq-guard-vectors.ts
// Do not hand-edit.

#[test_only]
module pq_guard::test_vectors;

public fun sender(): address { @0x0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a }

public fun pk(): vector<u8> { x"${hex(pkBytes)}" }

public fun action_digest_0(): vector<u8> { x"${hex(action0)}" }
public fun signature_for_nonce_0(): vector<u8> { x"${hex(sig0)}" }

public fun action_digest_1(): vector<u8> { x"${hex(action1)}" }
public fun signature_for_nonce_1(): vector<u8> { x"${hex(sig1)}" }
`;

process.stdout.write(out);
